### ISSUE TITLE
执行Demo报错

### ISSUE THREAD

**Issue by liminghe-li** [williamfzc/work_with_stagesepx#2]
我在clone代码后执行程序，在执行classify_with_model.py的时候报错
报错信息如下：
Traceback (most recent call last):
  File "/Users/liminghe/work_with_stagesepx/dynamic/classify_with_model.py", line 25, in <module>
    classify_result = cl.classify(video, stable, keep_data=True)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/stagesepx/classifier/base.py", line 439, in classify
    result = self._classify_frame(frame, *args, **kwargs)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/stagesepx/classifier/keras.py", line 199, in _classify_frame
    return self.predict_with_object(frame.data)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/stagesepx/classifier/keras.py", line 194, in predict_with_object
    frame = np.expand_dims(frame, axis=[0, -1])
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 579, in expand_dims
    if axis > a.ndim or axis < -a.ndim - 1:
TypeError: '>' not supported between instances of 'list' and 'int'

我的python版本3.7，numpy=1.16，keras=2.3.1
期待回复~

**Comment by williamfzc** [comment]
https://github.com/williamfzc/stagesepx/blob/4c5849b0041a86228da79921dd36e5e842abe612/setup.py#L34

numpy 问题

**Comment by liminghe-li** [comment]
感谢~
