### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by jiangzhengw** [williamfzc/work_with_stagesepx#7]
Traceback (most recent call last):
  File "D:/PythonPro/work_with_stagesepx/dynamic/train_model.py", line 13, in <module>
    cl.train(data_home)
  File "D:\Python\Python37\lib\site-packages\stagesepx\classifier\keras.py", line 170, in train
    validation_steps=self.nb_validation_samples // self.batch_size,
  File "D:\Python\Python37\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Python\Python37\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "D:\Python\Python37\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\keras\backend.py", line 3792, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "D:\Python\Python37\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Received a label value of 13 which is outside the valid range of [0, 12).  Label values: 4 10 1 0 0 7 10 7 0 10 3 4 13 13 3 0 2 8 3 9 7 10 0 8 2 3 3 12 0 10 7 13
	 [[node loss/activation_5_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at \Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_1036]

Function call stack:
keras_scratch_graph

**Comment by williamfzc** [comment]
参考下 https://github.com/williamfzc/stagesepx/issues/112
另外最好升级下stagesepx版本

**Comment by jiangzhengw** [comment]
好滴，谢谢大佬
